### ISSUE TITLE
Market List

### ISSUE THREAD

**Issue by firstdayofjune** [firstdayofjune/marktzeit#4]
As a user I can scroll through a list of supermarkets.
For every market, I can see:

- The type of the Market (e.g. Lidl, Edeka, REWE, Penny, Netto, Bio Company, Denn's)
- The address (Friedrichstraße 142, 10117 Berlin)
- The opening hours: (07:00 - 22:00, "closed today"/"Heute geschlossen", multiple opening hours per day possible and broken into multiple lines)
- The number of Slots which are still available throughout the rest of the day
- A call-to-action button: "Book a slot"/"Slot buchen" for every supermarket, with slots available

When I click the "Book a slot" button, I will be forwarded to the booking page of the supermarket

**Comment by shiwangsingh84** [comment]
done
